### ISSUE TITLE
DEMO代码运行失败了！

### ISSUE THREAD

**Issue by blusewang** [chenmnkken/gulp-seajs-combo#10]
var gulp = require( 'gulp' ),
    seajsCombo = require( 'gulp-seajs-combo' );

gulp.task('default', function() {

}) ;
gulp.task( 'seajs', function(){
    return gulp.src( 'resources/assets/js/main.js' )
        .pipe( seajsCombo({'ignore':['wx']}) )
        .pipe( gulp.task('public/js') );
});

[15:19:18] Using gulpfile ~/www/vhost/wgjv2/gulpfile.js
[15:19:18] Starting 'seajs'...
[15:19:18] Finished 'seajs' after 8.85 ms
[15:19:18] gulp-seajs-cmobo error: undefined is not a function
TypeError: undefined is not a function
    at write (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
    at emitReadable_ (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
    at emitReadable (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
    at readableAddChunk (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
    at DestroyableTransform.Readable.push (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
    at DestroyableTransform.Transform.push (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
    at afterTransform (/home/bluse/www/vhost/wgjv2/node_modules/gulp-seajs-combo/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:101:12)

**Comment by chenmnkken** [comment]
跟踪错误栈试试？

**Comment by blusewang** [comment]
这个DEMO代码过时了！
return gulp.src( 'resources/assets/js/main.js' )
.pipe( seajsCombo({'ignore':['wx']}) )
.pipe( gulp.task('public/js') );
});
应该写成：
return gulp.src( 'resources/assets/js/main.js' )
.pipe( seajsCombo({'ignore':['wx']}) )
.pipe( gulp.dest('public/js') );
});

**Comment by chenmnkken** [comment]
我去，本来就是 gulp.dest 啊，gulp.task 用来新建一个任务的。

**Comment by blusewang** [comment]
![image](https://cloud.githubusercontent.com/assets/1764005/11435479/f9e85c34-9515-11e5-8732-30e077253160.png)
